### ISSUE TITLE
Build for windows using clang

### ISSUE THREAD

**Issue by projectitis** [napi-bindings/quickjs-build#11]
Hi there,

Any tips to compile for windows using clang?

Best regards,
Peter

**Comment by NickNaso** [comment]
Hi @projectitis,
change the compiler should be simple, you only need to set the `CMAKE_C_COMPILER` environment variable like reported below:

```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -G "Ninja" -S ./ -B ./build
```
I installed the `Clang` directly on my Windows machine, but when I run the build: `cmake --build ./build` I get the error like I reported below:
![Immagine 2021-08-23 171826](https://user-images.githubusercontent.com/387506/130472942-81ed4825-b2d7-491a-92f3-6c5ca81ec1fa.png)
The only think that you can try to do is to install `Clang` non `MSYS` and compile  the project with it.
Could this work for you?

**Comment by NickNaso** [comment]
Hi @projectitis,
today I tried to use `Clang` on Windows and I report the steps I followed to compile the project:

- Install `CMake`  (version 3.17.2)
- Install `Ninja` (1.10.12) Ninja is the only generator supported for Clang (https://ninja-build.org/)
- Install MSYS (https://www.msys2.org/)
- Open MSYS console and install `Clang`:
    -  `pacman -S mingw-w64-x86_64-clang`
- Open Windows console and go to folder project and run the following commands:
    -  `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -G "Ninja" -S ./ -B ./build`  
    - ` cmake --build ./build`

![Immagine 2021-10-05 105843](https://user-images.githubusercontent.com/387506/135992966-6aee8d3b-d10e-425f-89fe-793bc83b88bc.png)

 You will obtain come wornings but it worked for me. I hope this help you.
