### ISSUE TITLE
M1 version

### ISSUE THREAD

**Issue by gengjiawen** [napi-bindings/quickjs-build#13]
Got a M1 by Installment payments. 

Not sure upload binary here so we can put it on release page works for you ?

**Comment by NickNaso** [comment]
Hi @gengjiawen,
I did some researches we could create a build for M1 cross-compiling for `arm64` on x86_64 runners adding 
`arch arm64` to CFLAGS, CXXFLAGS and LDFLAGS or set `-DCMAKE_OSX_ARCHITECTURES=arm64` In CMake.
What do you think about this solution?

**Comment by gengjiawen** [comment]
If it works, it surely be good

**Comment by gengjiawen** [comment]
@NickNaso Do you mind upload m1 version to https://github.com/napi-bindings/quickjs-build/releases

**Comment by NickNaso** [comment]
Yes, sure I can upload your version post it here.

**Comment by gengjiawen** [comment]
[qjs-macOS-arm64.zip](https://github.com/napi-bindings/quickjs-build/files/11340495/qjs-macOS-arm64.zip)

**Comment by gengjiawen** [comment]
> Yes, sure I can upload your version please post it here.

@NickNaso

**Comment by NickNaso** [comment]
Hi @gengjiawen I created the new release 6.0.0 to bring the last changes and I uploaded your binaries for m1 version to the new release.

**Comment by gengjiawen** [comment]
Thx
