### ISSUE TITLE
Does this include NAPI bindings for QuickJS?

### ISSUE THREAD

**Issue by ammarahm-ed** [napi-bindings/quickjs-build#16]
If not, are there some bindings that already exist in OSS since I am not able to find any?

**Comment by NickNaso** [comment]
Sorry @ammarahm-ed this not include the `Node-API` (N-API) implementation is only the build for the `quickjs`. I don't know the existence of other `Node-API` binding for `quickjs`.

**Comment by ammarahm-ed** [comment]
Thanks for replying. I will close this.
